import React, { useEffect, useState } from "react";

import {
  hubspot,
  Text,
  Divider,
  Flex,
  LoadingSpinner,
  EmptyState,
  Alert,
  Link,
  Image,
  Heading,
  Tag,
  Table,
  TableHead,
  TableRow,
  TableHeader,
  TableBody,
  TableCell,
} from "@hubspot/ui-extensions";

/**
 * File metadata returned by the backend
 */
interface FileInfo {
  id: string;
  name: string;
  extension: string;
  url: string;
  size: number;
  // SECURITY: Backend generates time-limited, single-use tokens for secure file access
  viewerToken?: string;
}

/**
 * Entry point for HubSpot UI Extension
 */
hubspot.extend(({ context }) => {
  return <DocumentBrowser context={context} />;
});

/**
 * Nutrient logo
 */
const Logo = ({ backendUrl }: { backendUrl: string }) => (
  <Image
    src={`${backendUrl}/logo.svg`}
    alt="Nutrient Logo"
    width={40}
    height={40}
  />
);

/**
 * File type color mapping
 */
const getFileTypeColor = (
  extension: string
): "default" | "success" | "warning" | "error" | "info" => {
  switch (extension.toLowerCase()) {
    case "pdf":
      return "error";
    case "doc":
    case "docx":
      return "info";
    case "xls":
    case "xlsx":
      return "success";
    case "ppt":
    case "pptx":
      return "warning";
    default:
      return "default";
  }
};

/**
 * Main document browser component
 */
const DocumentBrowser: React.FC<{ context: any }> = ({ context }) => {
  const [files, setFiles] = useState<FileInfo[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // Backend URL - Uses local.json proxy during development
  // In production, update this to your actual backend URL
  const BACKEND_URL = "https://xxxxxx-hubspot-backend.azurewebsites.net";

  // SECURITY BEST PRACTICE:
  // Backend validates requests using HubSpot origin headers and generates time-limited
  // viewer tokens (15 min expiry) for each file. No secrets exposed in frontend.

  /**
   * Fetch files for the current contact
   */
  useEffect(() => {
    const fetchFiles = async () => {
      try {
        // Get the current contact ID from HubSpot context
        const contactId = context.crm.objectId;

        if (!contactId) {
          throw new Error("No contact ID found");
        }

        // SECURE APPROACH:
        // Backend validates request origin (HubSpot domains) via validateHubSpotRequest middleware
        // No API key needed - HubSpot origin headers provide authentication
        const response = await hubspot.fetch(`${BACKEND_URL}/api/contact-files/${contactId}`);

        if (!response.ok) {
          throw new Error(`Backend returned ${response.status}`);
        }

        const data = await response.json();

        if (!data.success) {
          throw new Error(data.error || "Failed to load files");
        }

        setFiles(data.files || []);
      } catch (err: any) {
        setError(err.message || "Failed to load documents");
      } finally {
        setLoading(false);
      }
    };

    fetchFiles();
  }, [context]);

  /**
   * Viewer URL builder
   *
   * SECURE APPROACH:
   * Uses time-limited, file-specific viewer token generated by backend (15 min expiry)
   * Token validates: correct fileId, not expired, not already used
   * Backend generates new tokens on each request via generateViewerToken()
   */
  const getViewerUrl = (file: FileInfo) =>
    `${BACKEND_URL}/viewer/${file.id}?filename=${encodeURIComponent(file.name)}&token=${file.viewerToken || ''}`;

  // -------------------------
  // UI States
  // -------------------------

  if (loading) {
    return (
      <Flex direction="column" gap="md" align="center">
        <LoadingSpinner label="Loading documents..." />
      </Flex>
    );
  }

  if (error) {
    return (
      <Flex direction="column" gap="md">
        <EmptyState title="Error" layout="vertical">
          <Text>{error}</Text>
        </EmptyState>
        <Alert title="Troubleshooting" variant="warning">
          <Text variant="microcopy">
            1. Ensure the backend is running at {BACKEND_URL}
          </Text>
          <Text variant="microcopy">
            2. Verify HUBSPOT_PRIVATE_APP_TOKEN is set
          </Text>
          <Text variant="microcopy">
            3. Confirm backend endpoints are accessible
          </Text>
        </Alert>
      </Flex>
    );
  }

  if (files.length === 0) {
    return (
      <EmptyState title="No documents" layout="vertical">
        <Text>No files available.</Text>
      </EmptyState>
    );
  }

  // -------------------------
  // Main UI
  // -------------------------

  return (
    <Flex direction="column" gap="md">
      {/* Header */}
      <Flex direction="row" gap="md" align="center">
        <Logo backendUrl={BACKEND_URL} />
        <Flex direction="column" gap="flush">
          <Heading>Document Editor</Heading>
          <Text variant="microcopy">Powered by Nutrient</Text>
        </Flex>
      </Flex>

      {/* Document count */}
      <Flex direction="row" gap="sm" align="center">
        <Tag variant="default">{files.length} Documents</Tag>
      </Flex>

      <Divider />

      {/* Document table */}
      <Table bordered paginated={false}>
        <TableHead>
          <TableRow>
            <TableHeader>Document Name</TableHeader>
            <TableHeader width="min">Type</TableHeader>
          </TableRow>
        </TableHead>
        <TableBody>
          {files.map((file) => (
            <TableRow key={file.id}>
              <TableCell>
                <Link href={getViewerUrl(file)}>
                  {file.name}
                </Link>
              </TableCell>
              <TableCell width="min">
                <Tag variant={getFileTypeColor(file.extension)}>
                  {file.extension.toUpperCase()}
                </Tag>
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </Flex>
  );
};